version: "3.2"

services:
  dev:
    container_name: societal-node
    image: societal/societal-node:latest
    working_dir: /societal-node
    ports:
      - "9944:9944"
      - "9933:9933"
    environment:
      - CARGO_HOME=/var/www/societal-node/.cargo
    volumes:
      - .:/var/www/societal-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: /usr/local/bin/societal-node --dev --enable-offchain-indexing true --rpc-external --ws-external --rpc-cors=all --unsafe-ws-external --unsafe-rpc-external
