## Image of Parachain Societal Node.
##
image:
  repository: parity/polkadot-parachain
  tag: 0.9.400

node:
  role: collator
  isParachain: true
  command: polkadot-parachain

  customChainspecUrl: "https://societal-dev.s3.amazonaws.com/raw-asset-hub-chainspec.json"
  forceDownloadChainspec: true

  allowUnsafeRpcMethods: Unsafe

  chainData:
    pruning: archive
    volumeSize: 50Gi
    storageClass: gp2-custom-resize

  chainKeystore:
    storageClass: gp2-custom-resize

  collatorRelayChain:
    customChainspecUrl: "https://societal-dev.s3.amazonaws.com/raw-local-chainspec.json"
    chainData:
      volumeSize: 50Gi
      storageClass: gp2-custom-resize
    chainKeystore:
      storageClass: gp2-custom-resize

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

## Creates an ingress resource
##
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-development
    nginx.ingress.kubernetes.io/rewrite-target: /
  rules:
    - host: asset-hub-node-rpc.dev.sctl.link
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: asset-hub-node
                port:
                  number: 9933
    - host: asset-hub-node-ws.dev.sctl.link
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: asset-hub-node
                port:
                  number: 9944
  tls:
    - hosts:
        - asset-hub-node-rpc.dev.sctl.link
      secretName: asset-hub-rpc-tls-secret
    - hosts:
        - asset-hub-node-ws.dev.sctl.link
      secretName: asset-hub-ws-tls-secret
