## Image of Societal Node.
##
image:
  repository: societal/societal-node
  tag: solo-latest

## Deploy a substrate node
## ref: https://docs.substrate.io/tutorials/v3/private-network/
node:
  chain: local

  role: validator

  command: societal-node

  customChainspecPath: ""

  # allowUnsafeRpcMethods: Unsafe

  # Enable Offchain Indexing.
  # https://docs.substrate.io/fundamentals/offchain-operations/
  enableOffchainIndexing: true

  chainData:
    volumeSize: 20Gi
    storageClass: gp2

  chainKeystore:
    storageClass: gp2

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

  ## Creates an ingress resource
  ##
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-development
      nginx.ingress.kubernetes.io/rewrite-target: /
    rules:
      - host: node-rpc.dev.sctl.link
        http:
          paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                service:
                  name: societal-node
                  port:
                    number: 9933
      - host: node-ws.dev.sctl.link
        http:
          paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                service:
                  name: societal-node
                  port:
                    number: 9944
    tls:
      - hosts:
          - node-rpc.dev.sctl.link
        secretName: societal-node-rpc-tls-secret
      - hosts:
          - node-ws.dev.sctl.link
        secretName: societal-node-ws-tls-secret
