apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-custom-resize
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
mountOptions:
  - debug
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
