## Image of Parachain Societal Node.
##
image:
  repository: societal/societal-node
  tag: latest

node:
  role: collator
  isParachain: true
  command: societal-node
  
  customChainspecUrl: "https://societal-dev.s3.amazonaws.com/raw-parachain-chainspec.json"
  forceDownloadChainspec: true
  
  allowUnsafeRpcMethods: Unsafe

  # Enable Offchain Indexing.
  # https://docs.substrate.io/fundamentals/offchain-operations/
  enableOffchainIndexing: true

  chainData:
    pruning: archive
    volumeSize: 50Gi
    storageClass: gp2-custom-resize

  chainKeystore:
    storageClass: gp2-custom-resize

  collatorRelayChain:
    customChainspecUrl: "https://societal-dev.s3.amazonaws.com/raw-local-chainspec.json"
    chainData:
      volumeSize: 50Gi
      storageClass: gp2-custom-resize
    chainKeystore:
      storageClass: gp2-custom-resize

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

  ## Creates an ingress resource
  ##
ingress:
   enabled: true
   ingressClassName: nginx
   annotations:
     cert-manager.io/cluster-issuer: letsencrypt-development
     nginx.ingress.kubernetes.io/rewrite-target: /
   rules:
     - host: node-rpc.testnet.sctl.link
       http:
         paths:
           - path: /
             pathType: ImplementationSpecific
             backend:
               service:
                 name: societal-node
                 port:
                   number: 9933
     - host: node-ws.testnet.sctl.link
       http:
         paths:
           - path: /
             pathType: ImplementationSpecific
             backend:
               service:
                 name: societal-node
                 port:
                   number: 9944
   tls:
     - hosts:
         - node-rpc.testnet.sctl.link
       secretName: societal-node-rpc-tls-secret
     - hosts:
         - node-ws.testnet.sctl.link
       secretName: societal-node-ws-tls-secret
