## Image of Parachain Societal Node.
##
image:
  repository: societal/societal-node
  tag: parachain-latest

node:
  role: collator
  isParachain: true
  command: societal-node
  
  customChainspecUrl: "https://societal-dev.s3.amazonaws.com/raw-parachain-chainspec-2001.json"
  forceDownloadChainspec: true
  
  allowUnsafeRpcMethods: Unsafe

  chainData:
    volumeSize: 20Gi
    storageClass: gp2-custom

  chainKeystore:
    storageClass: gp2-custom

  collatorRelayChain:
    customChainspecUrl: "https://societal-dev.s3.amazonaws.com/raw-local-chainspec.json"
    chainData:
      volumeSize: 20Gi
      storageClass: gp2-custom
    chainKeystore:
      storageClass: gp2-custom

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

  ## Creates an ingress resource
  ##
ingress:
   enabled: true
   ingressClassName: nginx
   annotations:
     cert-manager.io/cluster-issuer: letsencrypt-development
     nginx.ingress.kubernetes.io/rewrite-target: /
   rules:
     - host: node-rpc-rococo-2001.dev.sctl.link
       http:
         paths:
           - path: /
             pathType: ImplementationSpecific
             backend:
               service:
                 name: societal-parachain-node-2001
                 port:
                   number: 9933
     - host: node-ws-rococo-2001.dev.sctl.link
       http:
         paths:
           - path: /
             pathType: ImplementationSpecific
             backend:
               service:
                 name: societal-parachain-node-2001
                 port:
                   number: 9944
   tls:
     - hosts:
         - node-rpc-rococo-2001.dev.sctl.link
       secretName: societal-parachain-node-2001-rpc-tls-secret
     - hosts:
         - node-ws-rococo-2001.dev.sctl.link
       secretName: societal-parachain-node-2001-ws-tls-secret
