name: 'Docker Build Publish'
runs:
  using: 'composite'
  steps:
  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v3
    with:
      images: |
        ${{ env.DOCKER_REPO }}
      tags: |
        type=raw,value=latest
        type=raw,value=${{ env.DOCKER_ENV_TAG }}
        type=raw,value=${{ env.RELEASE_VERSION }}
        type=ref,event=branch,suffix=-latest
        type=sha,prefix=,format=long

  - name: Set up QEMU
    uses: docker/setup-qemu-action@v2

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Build And Push
    uses: docker/build-push-action@v2
    with:
      context: .
      file: Dockerfile
      build-args: |
        CARGO_FEATURES=${{ github.event.inputs.features }}
      platforms: ${{ github.event.inputs.platform }}
      tags: ${{ steps.meta.outputs.tags }}
      push: true
      cache-from: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
      cache-to: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache,mode=max
